# Generated by Django 5.1.1 on 2026-01-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_live_match_match_pairing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='pairing_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='pairing_type',
            field=models.CharField(choices=[('RANDOM', 'Random (Tournament)'), ('ROUND_ROBIN', 'Round Robin'), ('CUSTOM_TOURNAMENT', 'Custom Tournament'), ('CUSTOM_ROUND_ROBIN', 'Custom Round Robin')], default='RANDOM', max_length=30),
        ),
    ]
