# Generated by Django 5.1.1 on 2026-01-04 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('tournaments', '0003_remove_match_pairing_type_tournament_pairing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='TournamentMatch',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.UniqueConstraint(fields=('tournament', 'player1', 'player2'), name='unique_pair'),
        ),
    ]
