# Generated by Django 5.1.1 on 2026-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_rename_match_tournamentmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='increment_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
