# Generated by Django 5.1.1 on 2026-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentmatch_increment_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='increment_seconds',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='tournament',
            name='base_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='increment_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
