# Generated by Django 5.1.1 on 2026-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_tournamentmatch_increment_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='fen',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_created',
            field=models.BooleanField(default=False),
        ),
    ]
