# Generated by Django 5.2.6 on 2026-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_remove_tournamentmatch_fen_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentmatch",
            options={"ordering": ["-round_number", "-scheduled_at"]},
        ),
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="round_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="pairing_type",
            field=models.CharField(
                choices=[
                    ("RANDOM", "Random (Tournament)"),
                    ("ROUND_ROBIN", "Round Robin"),
                    ("SWISS", "Swiss System"),
                    ("KNOCKOUT", "Knockout (Single Elimination)"),
                    ("CUSTOM_TOURNAMENT", "Custom Tournament"),
                    ("CUSTOM_ROUND_ROBIN", "Custom Round Robin"),
                ],
                default="RANDOM",
                max_length=30,
            ),
        ),
    ]
