# Generated by Django 4.2.16 on 2025-09-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_rank_userprofile_last_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
    ]
