# Generated by Django 5.2.6 on 2025-12-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT", "Waiting"),
                            ("LIVE", "Live"),
                            ("END", "Ended"),
                        ],
                        default="WAIT",
                        max_length=10,
                    ),
                ),
                (
                    "current_fen",
                    models.TextField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
                    ),
                ),
                ("move_history", models.JSONField(default=list)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1-0", "White Wins"),
                            ("0-1", "Black Wins"),
                            ("1/2-1/2", "Draw"),
                            ("*", "Ongoing"),
                        ],
                        default="*",
                        max_length=10,
                    ),
                ),
                ("white_connected", models.BooleanField(default=False)),
                ("black_connected", models.BooleanField(default=False)),
                (
                    "player_black",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_white",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
