# Generated by Django 5.1.1 on 2026-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
